heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy an elasticsearch cluster on the
  Rackspace Cloud.

parameters:

  server_hostname:
    description: Hostname for the servers.
    type: string
    default: es

  ssh_keypair_name:
    description: Nova keypair name for ssh access to the servers
    type: string
    default: jgbes

  es_node_count:
    description: Number of nodes to create
    type: number
    default: 2

resources:

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: ssh_keypair_name }
      save_private_key: true

  es_network:
      type: Rackspace::Cloud::Network
      properties:
        label: es_network
        cidr: 192.168.0.0/24

  es_nodes:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: { get_param: es_node_count }
      resource_def:
        type: https://point_to_the_node_file/es_node.yaml
        properties:
          server_hostname:  { get_param: server_hostname }
          ssh_keypair_name: { get_param: ssh_keypair_name }
          es_network_id:    { get_resource: es_network }
          ssh_private_key:  { get_attr: [ssh_key, private_key] }

#  es_server:
#    type: "Rackspace::Cloud::Server"
#    properties:
#      name: es
#      flavor: 4 GB Performance
#      image: Ubuntu 12.04 LTS (Precise Pangolin)
#      key_name: { get_resource: ssh_key }
#      networks:
#      - uuid: "00000000-0000-0000-0000-000000000000"
#      - uuid: "11111111-1111-1111-1111-111111111111"
#      - uuid: { get_resource: es_network }
#
#  es_pre_setup:
#    type: "OS::Heat::ChefSolo"
#    depends_on: es_server
#    properties:
#      username: root
#      private_key: { get_attr: [ssh_key, private_key] }
#      host: { get_attr: [es_server, accessIPv4] }
#      Berksfile: |
#        site :opscode
#        cookbook 'apt'
#        cookbook 'build-essential'
#      node:
#        run_list: [ "recipe[apt]",
#                    "recipe[build-essential]"]
#
#  es_setup:
#    type: "OS::Heat::ChefSolo"
#    depends_on: es_pre_setup
#    properties:
#      username: root
#      private_key: { get_attr: [ssh_key, private_key] }
#      host: { get_attr: [es_server, accessIPv4] }
#      Berksfile: |
#        site :opscode
#        cookbook 'java'
#        cookbook 'rax-elasticsearch',
#          :git => 'https://github.com/JasonBoyles/cookbook-rax-elasticsearch.git'
#      node:
#        elasticsearch:
#          cluster:
#            name: heated_cluster
#        run_list: ["recipe[rax-elasticsearch]"]
#
outputs:
  private_key:
    value: { get_attr: [ssh_key, private_key] }
