heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy an elasticsearch cluster on the
  Rackspace Cloud.


parameters:

  server_hostname:
    description: Hostname for the servers.
    type: string
    default: es

  ssh_keypair_name:
    description: Nova keypair name for ssh access to the servers
    type: string
    default: jgbes

  es_node_count:
    description: Number of nodes to create
    type: number
    default: 2


resources:

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: ssh_keypair_name }
      save_private_key: true

  es_network:
      type: Rackspace::Cloud::Network
      properties:
        label: es_network
        cidr: 192.168.0.0/24

  es_nodes:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: { get_param: es_node_count }
      resource_def:
        type: http://drop.duncancreek.net/es_node.yaml
        properties:
          server_hostname:  { get_param: server_hostname }
          ssh_keypair_name: { get_param: ssh_keypair_name }
          ssh_private_key:  { get_attr: [ssh_key, private_key] }
          es_network_id:    { get_resource: es_network }


outputs:
  private_key:
    value: { get_attr: [ssh_key, private_key] }
